export type ChurchLevel =
  | 'Fellowship'
  | 'Bacenta'
  | 'Constituency'
  | 'Council'
  | 'Stream'
  | 'GatheringService'
  | 'Oversight'
  | 'Denomination'
  | 'Sonta'
  | 'Hub'
  | 'Ministry'
  | 'Federalministry'
